/* feeds.js - live data engine. Some publications (interest rates, exchange rates, money and credit, bond and equity markets, balance of payments, reserves, national-government cash flow,
   business-cycle indicators, national accounts, government operations and debt, investment position ...) are not downloaded and parsed by the updater: the browser reads them from the
   Reserve Bank's public Web API and builds ordinary publications out of them, which then sit in the Series Explorer and on their tabs like every other publication.
   - js/feeds-catalog.js (generated by tools/Build-FeedCatalog.py) lists every series: code, group, frequency, unit and how eagerly it is loaded.
   - data/live/ (built at deploy time by tools/Build-FeedSnapshot.py) carries the FULL history in a few part files: 'core' (every monthly / quarterly / annual group; loaded at start) and
     'rates-daily', 'fx-daily', 'sdds' (loaded when a section needs them, or in idle time for the small ones). index.js lists the parts and the build time.
   - The browser then tops up only what is newer than the snapshot (and stores the result in IndexedDB); a series the snapshot does not hold is fetched whole. A tail is re-read only when the API
     says a release moved, or for daily series after 30 minutes. One request serves a series even when it appears twice (monthly view and daily view).
   - Nothing blocks the page: the StatsSA tabs never wait for this. Tabs ask for what they need (Feeds.load / ensureCodes) and redraw when it arrives (events "feedsupdate" / "feedsrefreshed").
   - If the API is unreachable the shipped history and the stored copy are used. Failures are per series. */
(function () {
'use strict';
const CAT = window.FEEDS_CATALOG;
if (!CAT || !window.Kit || !window.EQ) { window.Feeds = null; return; }
const Store = Kit.store, API = CAT.api;
const TAB = 'markets';
const ENT = CAT.series.map(e => Object.assign({}, e, { k: e.p + '|' + e.id }));
const byKey = new Map(ENT.map(e => [e.k, e])), byPub = {}, pubDef = {}, byCode = {};
CAT.pubs.forEach(p => { pubDef[p.code] = p; byPub[p.code] = []; Kit.PUB_SHORT[p.code] = p.short; });
ENT.forEach(e => { byPub[e.p].push(e); (byCode[e.c] = byCode[e.c] || []).push(e); });
const partOf = e => (pubDef[e.p] && pubDef[e.p].part) || 'core';
const FROM = { M: 1995, Q: 1995, A: 2000, D: 2015 };                                  // first year fetched for a series the snapshot does not hold
const TTL = { D: 30 * 60e3, M: 6 * 3600e3, Q: 12 * 3600e3, A: 24 * 3600e3 };          // how long a stored series is trusted before its tail is re-read
const KB_PER_OBS = 0.235;                                                              // the API sends ~235 bytes of JSON per observation
const FILL_DAYS = 10;                                                                  // a daily series carries its last value across days with no published figure, up to this many days

const recs = new Map();                                                                // k -> { k, obs, hist?, fetchedAt, stamp, from }  (hist: monthly figures of a daily series before obs begins)
const inflight = new Map(), errors = new Map();
const partState = new Map();                                                           // name -> Promise<boolean> (true = loaded)
let rel = null, relPromise = null, relList = [], snap = {}, snapAt = 0, snapInfo = null, isReady = false, readyResolve;
const readyP = new Promise(r => { readyResolve = r; });
const progress = { total: 0, done: 0, failed: 0, kb: 0, active: false };
const refreshed = new Set();                                                           // publications whose already-stored series just received newer data
const hidden = {};                                                                     // series kept only for cross-checks (never shown as series)

/* ------------------------------------------------------------------ small helpers */
const todayISO = () => new Date().toISOString().slice(0, 10);
function toF(x) { if (x == null || x === '') return null; if (typeof x === 'number') return isFinite(x) ? x : null; const f = parseFloat(String(x).replace(/[\s  ]/g, '').replace(',', '.')); return isFinite(f) ? f : null; }
function emit(pubs) { try { document.dispatchEvent(new CustomEvent('feedsupdate', { detail: { pubs: pubs || [] } })); } catch (e) {} }
const addDays = (iso, n) => new Date(Date.parse(iso + 'T00:00:00Z') + n * 864e5).toISOString().slice(0, 10);
const mIdx = p => +p.slice(0, 4) * 12 + (+p.slice(5, 7) - 1), mLab = i => Math.floor(i / 12) + '-' + String(i % 12 + 1).padStart(2, '0');
const qIdx = p => +p.slice(0, 4) * 4 + Math.ceil(+p.slice(5, 7) / 3) - 1, qLab = i => Math.floor(i / 4) + '-Q' + (i % 4 + 1);
const aIdx = p => +p.slice(0, 4), aLab = i => String(i);

/* ------------------------------------------------------------------ cache (IndexedDB, with an in-memory fallback) */
let db = null;
function openDB() {
  return new Promise(res => {
    try {
      const rq = indexedDB.open('pulse-feeds', 1);
      rq.onupgradeneeded = () => { rq.result.createObjectStore('series', { keyPath: 'k' }); };
      rq.onsuccess = () => { db = rq.result; res(db); };
      rq.onerror = rq.onblocked = () => res(null);
    } catch (e) { res(null); }
  });
}
function idbAll() { return new Promise(res => { if (!db) return res([]); try { const rq = db.transaction('series').objectStore('series').getAll(); rq.onsuccess = () => res(rq.result || []); rq.onerror = () => res([]); } catch (e) { res([]); } }); }
function idbPut(rec) { if (!db) return; try { db.transaction('series', 'readwrite').objectStore('series').put(rec); } catch (e) {} }
function idbClear() { return new Promise(res => { if (!db) return res(); try { const tx = db.transaction('series', 'readwrite'); tx.objectStore('series').clear(); tx.oncomplete = () => res(); tx.onerror = () => res(); } catch (e) { res(); } }); }

/* ------------------------------------------------------------------ network */
async function jget(url, timeout, tries) {
  let last = null;
  for (let i = 0; i < (tries || 2); i++) {
    const ac = new AbortController(), to = setTimeout(() => ac.abort(), timeout || 60000);
    try {
      const r = await fetch(url, { signal: ac.signal, mode: 'cors', credentials: 'omit' });
      if (!r.ok) throw new Error('HTTP ' + r.status);
      const j = await r.json(); clearTimeout(to); return j;
    } catch (e) { clearTimeout(to); last = e; if (i + 1 < (tries || 2)) await new Promise(r => setTimeout(r, 800 * (i + 1))); }
  }
  throw last || new Error('request failed');
}
async function pool(jobs, n, fn) {
  let i = 0; const run = async () => { while (i < jobs.length) { const j = jobs[i++]; await fn(j); } };
  await Promise.all(Array.from({ length: Math.min(n, jobs.length) }, run));
}
function releaseStamps() {
  if (rel) return Promise.resolve(rel);
  if (!relPromise) relPromise = jget(API + '/WebIndicators/ReleaseOfSelectedData', 20000, 2).then(r => { rel = {}; relList = r || []; (r || []).forEach(x => { if (x.DataType) rel[x.DataType] = x.LastPeriod || ''; }); return rel; }).catch(() => { rel = {}; return rel; });
  return relPromise;
}
function parseRows(rows, daily) {
  const out = new Map();
  (rows || []).forEach(r => {
    const d = String(r.Period || '').slice(0, 10), v = toF(r.Value); if (!d || v == null) return;
    out.set(daily ? d : d.slice(0, 7), v);
  });
  return Array.from(out.entries()).sort((a, b) => a[0] < b[0] ? -1 : 1);
}
function startOf(e, rec) {                                                             // where a top-up for this entry starts
  const daily = e.f === 'D';
  const lastKey = rec ? (rec.obs.length ? rec.obs[rec.obs.length - 1][0] : (rec.hist ? mLab(mIdx(rec.hist.a) + rec.hist.v.length - 1) : null)) : null;
  if (!lastKey) return (e.from || FROM[e.f] || 1995) + '-01-01';
  let from = addDays(lastKey.length === 7 ? lastKey + '-01' : lastKey, daily ? -20 : e.f === 'M' ? -400 : e.f === 'Q' ? -500 : -800);
  if (daily && !e.dv) from = from.slice(0, 8) + '01';                                 // a month rebuilt from days must have ALL its days, or its average would replace a full-month figure with a part-month one
  return from;
}
function applyRows(e, rows) {                                                          // merge freshly fetched rows into this entry's stored record
  const rec = recs.get(e.k), daily = e.f === 'D', from = startOf(e, rec);
  const fresh = parseRows(rows, daily).filter(o => o[0] >= (daily ? from : from.slice(0, 7)));
  if (!fresh.length && !(rec && (rec.obs.length || rec.hist))) throw new Error('no observations');
  let obs;
  if (rec && rec.obs.length && fresh.length) { const cut = fresh[0][0]; obs = rec.obs.filter(o => o[0] < cut).concat(fresh); } else obs = fresh.length ? fresh : (rec ? rec.obs : []);
  const nrec = { k: e.k, obs, hist: rec ? rec.hist : undefined, from: rec ? rec.from : (e.from || FROM[e.f] || 1995), fetchedAt: Date.now(), stamp: (e.dt && rel && rel[e.dt]) || '' };
  if (rec && rec.obs.length && obs.length) { const o = rec.obs[rec.obs.length - 1], n = obs[obs.length - 1]; if (n[0] !== o[0] || n[1] !== o[1] || obs.length !== rec.obs.length) refreshed.add(e.p); }          // newer data arrived for something already shown
  recs.set(e.k, nrec); idbPut(nrec);
}
async function fetchCode(code, ents) {                                                 // ONE request serves every entry that uses this API code
  const from = ents.map(e => startOf(e, recs.get(e.k))).sort()[0], to = todayISO();
  const rows = await jget(API + '/WebIndicators/Shared/GetTimeseriesObservations/' + encodeURIComponent(code) + '/' + from + '/' + to, 120000, 2);
  progress.kb += rows ? Math.round(rows.length * KB_PER_OBS) : 0;
  ents.forEach(e => applyRows(e, rows));
}
function stale(e, rec) {
  if (!rec) return true;
  if (Date.now() - rec.fetchedAt < 60e3) return false;
  if (e.dt && rel && rel[e.dt]) return rel[e.dt] > (rec.stamp || '');            // a release-based series changes only when its release moves
  return Date.now() - rec.fetchedAt > (TTL[e.f] || TTL.M);
}

/* ------------------------------------------------------------------ observations -> a Pulse publication */
function points(e, obs, hist) {                                 // monthly / quarterly / annual -> [[index, value]] on the publication's own period axis
  if (e.f === 'D') {                                            // daily -> one value per month: the average, or the last day for a rate "in force"
    const g = new Map(), res = new Map(), need = e.a === 'last' ? 1 : 3;
    if (hist && hist.v) { const f0 = mIdx(hist.a); hist.v.forEach((x, i) => { if (x != null) res.set(f0 + i, x); }); }          // months already summarised in the snapshot
    obs.forEach(o => { const i = mIdx(o[0]); const a = g.get(i) || []; a.push(o[1]); g.set(i, a); });
    g.forEach((a, i) => { if (a.length >= need) res.set(i, e.a === 'last' ? a[a.length - 1] : a.reduce((s, x) => s + x, 0) / a.length); });     // months built from the days win
    return Array.from(res.entries()).sort((a, b) => a[0] - b[0]);
  }
  const ix = pubDef[e.p].freq === 'Q' ? qIdx : pubDef[e.p].freq === 'A' ? aIdx : mIdx;
  const m = new Map(); obs.forEach(o => m.set(ix(o[0]), o[1]));
  return Array.from(m.entries()).sort((a, b) => a[0] - b[0]);
}
function seriesMeta(e) {
  const sa = /seasonally adjusted|\(sa\)/i.test(e.n + ' ' + e.cat);
  return { id: e.id, measure: e.cat, name: e.n, sub: e.sub || '', geo: '', price: '', adj: sa ? 'sa' : 'nsa', unit: e.u, base: e.bs || '', label: e.cat + ' / ' + e.n,
    x: { Code: e.c, Frequency: e.dv ? 'Daily' : e.f === 'D' ? 'Daily (monthly ' + (e.a === 'last' ? 'month-end' : 'average') + ')' : ({ M: 'Monthly', Q: 'Quarterly', A: 'Annual' })[e.f] } };
}
function buildDailyPub(code) {                                  // a daily publication: the axis is every date on which any of its series has a figure; gaps inside a series carry the last value
  const def = pubDef[code], parts = [];
  byPub[code].forEach(e => { const rec = recs.get(e.k); if (!rec || !rec.obs.length) return; parts.push({ e, obs: rec.obs }); });
  if (!parts.length) return false;
  const all = new Set(); parts.forEach(p => p.obs.forEach(o => all.add(o[0])));
  const periods = Array.from(all).sort(), pos = new Map(periods.map((d, i) => [d, i])), dayN = periods.map(d => Date.parse(d + 'T00:00:00Z') / 864e5);
  const series = parts.map(({ e, obs }) => {
    const first = pos.get(obs[0][0]), last = pos.get(obs[obs.length - 1][0]), v = new Array(last - first + 1).fill(null);
    obs.forEach(o => { v[pos.get(o[0]) - first] = o[1]; });
    let prev = null, prevDay = 0;                                // carry the previous value across days with no figure (a holiday in one market), but not across a long break
    for (let i = 0; i < v.length; i++) { if (v[i] != null) { prev = v[i]; prevDay = dayN[first + i]; } else if (prev != null && dayN[first + i] - prevDay <= FILL_DAYS) v[i] = prev; }
    return Object.assign(seriesMeta(e), { s: first, v });
  });
  window.EQ.pubs[code] = { name: def.name, tab: TAB, freq: 'D', periods, series, notes: ['Daily figures; on days with no published figure the previous value is carried forward (up to ' + FILL_DAYS + ' days).'], empty: [], sources: 'Reserve Bank data service (history shipped with the site, recent days read live)', live: true };
  Store.addPub(code);
  return true;
}
function buildPub(code) {
  const def = pubDef[code]; if (def.freq === 'D') return buildDailyPub(code);
  const fq = def.freq, lab = fq === 'Q' ? qLab : fq === 'A' ? aLab : mLab;
  const parts = [];
  byPub[code].forEach(e => { const rec = recs.get(e.k); if (!rec || !(rec.obs.length || rec.hist)) return; const pts = points(e, rec.obs, rec.hist); if (e.hide) { hidden[e.c] = { e, pts }; return; } if (pts.length) parts.push({ e, pts }); });
  if (!parts.length) return false;
  let lo = Infinity, hi = -Infinity; parts.forEach(p => { lo = Math.min(lo, p.pts[0][0]); hi = Math.max(hi, p.pts[p.pts.length - 1][0]); });
  const periods = []; for (let i = lo; i <= hi; i++) periods.push(lab(i));
  const series = parts.map(({ e, pts }) => {
    const first = pts[0][0], last = pts[pts.length - 1][0], v = new Array(last - first + 1).fill(null);
    pts.forEach(([i, x]) => { v[i - first] = x; });
    return Object.assign(seriesMeta(e), { s: first - lo, v });
  });
  const notes = [];
  if (byPub[code].some(e => e.f === 'D')) notes.push('Built from daily figures; the latest month is the month so far.');
  window.EQ.pubs[code] = { name: def.name, tab: TAB, freq: fq, periods, series, notes, empty: [], sources: 'Reserve Bank data service (history shipped with the site, recent days read live)', live: true };
  Store.addPub(code);
  return true;
}
let pending = new Set(), timer = null;
function schedule(pub) {
  pending.add(pub);
  if (timer) return;
  timer = setTimeout(() => { timer = null; const ps = Array.from(pending); pending = new Set(); const done = ps.filter(buildPub); if (done.length) { updateHeader(); emit(done); } }, 350);
}
let lastTouch = Date.now();                                                           // the user's last click / key / scroll: views are not redrawn under their hands
['pointerdown', 'keydown', 'wheel', 'touchstart'].forEach(ev => window.addEventListener(ev, () => { lastTouch = Date.now(); }, { passive: true }));
let waitingRedraw = false;
function announceRefresh() {                                                          // tell the open view to redraw with the newer data: at once if it has been left alone for a minute (or the page is brand new), otherwise soon after
  const quiet = Date.now() - lastTouch > 60e3 || performance.now() < 30e3;
  if (quiet) { const ps = Array.from(refreshed); refreshed.clear(); try { document.dispatchEvent(new CustomEvent('feedsrefreshed', { detail: { pubs: ps } })); } catch (e) {} return; }
  if (waitingRedraw) return; waitingRedraw = true;
  setTimeout(() => { waitingRedraw = false; if (refreshed.size) announceRefresh(); }, 30e3);
}
function updateHeader() { const el = document.getElementById('hdrStat'); if (el) el.textContent = Store.all.length.toLocaleString('en-US') + ' series · ' + Store.pubs.length + ' publications'; }

/* ------------------------------------------------------------------ the shipped history (data/live/<part>.js) */
function decodeRec(r) {
  if (r.dv) {                                                   // daily view: first date + day gaps + values
    const obs = new Array(r.v.length); let day = Date.parse(r.a + 'T00:00:00Z') / 864e5;
    for (let i = 0; i < r.v.length; i++) { day += r.d[i]; obs[i] = [new Date(day * 864e5).toISOString().slice(0, 10), r.v[i]]; }
    return { obs };
  }
  if (r.f === 'D') return { obs: r.o || [], hist: r.v && r.a ? { a: r.a, v: r.v } : undefined };
  if (r.o) return { obs: r.o };
  const first = mIdx(r.a), st = r.st || 1, obs = [];
  r.v.forEach((x, i) => { if (x != null) obs.push([mLab(first + i * st), x]); });
  return { obs };
}
function mergePart(P) {
  if (!P || !P.series) return [];
  const touched = new Set();
  Object.keys(P.series).forEach(k => {
    const e = byKey.get(k); if (!e) return;
    const r = P.series[k], d = decodeRec(r), idb = recs.get(k), srec = { k, obs: d.obs, hist: d.hist, from: 0, fetchedAt: P.builtMs, stamp: r.s || '' };
    touched.add(e.p);
    if (!idb || srec.fetchedAt >= idb.fetchedAt) { recs.set(k, srec); return; }          // nothing stored here yet, or the shipped copy is the newer one
    if (e.f === 'D' && !e.dv) { if (!idb.hist && d.hist) idb.hist = d.hist; }              // this browser's copy is newer: lend it the shipped history
    else if (idb.obs.length && d.obs.length && d.obs[0][0] < idb.obs[0][0]) idb.obs = d.obs.filter(o => o[0] < idb.obs[0][0]).concat(idb.obs);
  });
  return Array.from(touched);
}
function loadPart(name) {                                                              // -> Promise<boolean>; each part is fetched once
  if (partState.has(name)) return partState.get(name);
  const ix = window.FEEDS_INDEX;
  if (!ix || !ix.parts || !ix.parts[name]) { const p = Promise.resolve(false); partState.set(name, p); return p; }
  const p = new Promise(res => {
    const done = ok => { if (!ok) partState.delete(name); res(ok); };
    if (window.FEEDS_PARTS && window.FEEDS_PARTS[name]) return done(true);
    const el = document.createElement('script'); el.async = true; el.src = 'data/live/' + name + '.js?v=' + ix.builtMs;
    el.onload = () => done(!!(window.FEEDS_PARTS && window.FEEDS_PARTS[name])); el.onerror = () => done(false);
    document.head.appendChild(el);
    setTimeout(() => { if (!(window.FEEDS_PARTS && window.FEEDS_PARTS[name])) done(false); }, 60000);
  }).then(async ok => {
    if (!ok) return false;
    const pubs = mergePart(window.FEEDS_PARTS[name]);
    for (const code of pubs) { buildPub(code); await new Promise(r => setTimeout(r, 0)); }       // one publication at a time, so the page is never held up
    if (pubs.length) { updateHeader(); emit(pubs); }
    return true;
  });
  partState.set(name, p);
  return p;
}
async function loadIndex() {                                                           // data/live/index.js is a script tag in index.html: wait for it (or its failure)
  if (window.FEEDS_INDEX || window.FEEDS_INDEX_FAILED) return window.FEEDS_INDEX || null;
  const el = document.getElementById('feedsIndex'); if (!el) return null;
  await new Promise(res => { el.addEventListener('load', res); el.addEventListener('error', res); setTimeout(res, 20000); });
  return window.FEEDS_INDEX || null;
}

/* ------------------------------------------------------------------ public API */
function entriesFor(spec) {                                                           // spec: array of series codes, or { tier, pubs }. A code that appears in both a monthly and a daily publication returns both entries.
  if (Array.isArray(spec)) { const out = []; spec.forEach(c => (byCode[c] || []).forEach(e => out.push(e))); return out; }
  return ENT.filter(e => (!spec.tier || e.t <= spec.tier) && (!spec.pubs || spec.pubs.indexOf(e.p) >= 0));
}
function estimate(entries) {                                                          // what has to be downloaded for entries that are not stored yet: whole parts (compressed) or, without a shipped copy, the raw series
  const ix = window.FEEDS_INDEX, partsNeeded = new Set(); let kb = 0, n = 0;
  const y = new Date().getFullYear();
  entries.forEach(e => {
    if (recs.has(e.k)) return; n++;
    const part = partOf(e);
    if (ix && ix.parts && ix.parts[part]) { if (!partsNeeded.has(part)) { partsNeeded.add(part); kb += ix.parts[part].gzip / 1024; } }
    else kb += KB_PER_OBS * (y - (e.from || FROM[e.f] || 1995) + 1) * (e.f === 'D' ? 252 : e.f === 'M' ? 12 : e.f === 'Q' ? 4 : 1);
  });
  return { series: n, mb: kb / 1024 };
}
async function load(entries) {
  entries = Array.from(new Set(entries));
  await readyP;                                                                          // the shipped core history and this browser's copy are in place first
  await Promise.all(Array.from(new Set(entries.filter(e => !recs.has(e.k)).map(partOf))).map(loadPart));      // other parts (daily histories, the IMF-standard tables) on demand
  await releaseStamps();
  const jobs = new Map();                                                                // API code -> entries that need a (partial or full) read
  entries.forEach(e => { if (!inflight.has(e.k) && stale(e, recs.get(e.k))) { (jobs.get(e.c) || jobs.set(e.c, []).get(e.c)).push(e); } });
  const waits = entries.filter(e => inflight.has(e.k)).map(e => inflight.get(e.k));
  const list = Array.from(jobs.entries());
  if (list.length) {
    progress.total += list.length; progress.active = true; emit([]);
    const res = new Map();
    list.forEach(([c, es]) => { const p = new Promise(r => res.set(c, r)); es.forEach(e => inflight.set(e.k, p)); waits.push(p); });          // registered up front, so a second request for the same series waits instead of fetching again
    pool(list, 4, async ([c, es]) => {
      try { await fetchCode(c, es); es.forEach(e => { errors.delete(e.k); schedule(e.p); }); }
      catch (err) { es.forEach(e => { if (!recs.has(e.k)) progress.failed++; errors.set(e.k, String(err && err.message || err)); }); }
      finally {
        progress.done++; es.forEach(e => inflight.delete(e.k)); res.get(c)();
        if (progress.done >= progress.total) { progress.active = false; progress.total = progress.done = progress.failed = progress.kb = 0; emit([]); } else if (progress.done % 6 === 0) emit([]);
      }
    });
  }
  await Promise.all(waits);
  entries.forEach(e => schedule(e.p));
  await new Promise(r => setTimeout(r, 600));
  if (refreshed.size) announceRefresh();
  return { missing: entries.filter(e => !recs.has(e.k)).length };
}
async function boot() {
  try {
    await openDB();
    (await idbAll()).forEach(r => { if (byKey.has(r.k) && ((r.obs && r.obs.length) || r.hist)) recs.set(r.k, r); });
    const ix = await loadIndex();
    if (ix) { snapInfo = { built: ix.built, ms: ix.builtMs, parts: ix.parts, releases: ix.releases }; await loadPart('core'); }
  } catch (e) { /* carry on with whatever is in memory */ }
  const pubs = new Set(); recs.forEach((r, k) => { const e = byKey.get(k); if (e && pubDef[e.p].part === 'core') pubs.add(e.p); });
  for (const p of pubs) { if (!Store.pubs.some(x => x.code === p)) buildPub(p); await new Promise(r => setTimeout(r, 0)); }
  if (pubs.size) { updateHeader(); emit(Array.from(pubs)); }
  isReady = true; readyResolve();
  snapshot().catch(() => {});                                                          // small: the headline rates for the Pulse tab
  const idle = window.requestIdleCallback || (f => setTimeout(f, 1500));
  idle(() => { ['rates-daily', 'sdds'].forEach(n => loadPart(n)); });                // the small parts join the Explorer in idle time; the big daily FX history waits until it is asked for
  if (recs.size) releaseStamps().then(() => { const cached = ENT.filter(e => recs.has(e.k) && stale(e, recs.get(e.k))); if (cached.length) load(cached); });
}
function refreshStale() { const stale_ = ENT.filter(e => recs.has(e.k) && stale(e, recs.get(e.k))); if (stale_.length && document.visibilityState !== 'hidden') { snapAt = 0; snapshot().catch(() => {}); return releaseStamps_().then(() => load(stale_)); } return Promise.resolve(); }
function releaseStamps_() { rel = null; relPromise = null; return releaseStamps(); }            // re-read which releases moved (the list is tiny)
setInterval(refreshStale, 10 * 60e3);
document.addEventListener('visibilitychange', () => { if (document.visibilityState === 'visible') refreshStale(); });
async function snapshot() {
  if (Date.now() - snapAt < 5 * 60e3 && Object.keys(snap).length) return snap;
  const [a, b, c] = await Promise.allSettled(['HomePageRates', 'CurrentMarketRates', 'HistoricalExchangeRatesDaily'].map(p => jget(API + '/WebIndicators/' + p, 20000, 2)));
  const out = {};
  [a, b, c].forEach(r => { if (r.status === 'fulfilled') (r.value || []).forEach(x => { if (x.TimeseriesCode) out[x.TimeseriesCode] = { code: x.TimeseriesCode, name: x.Name, value: toF(x.Value), date: String(x.Date || '').slice(0, 10), up: x.UpDown, section: x.SectionName }; }); });
  if (Object.keys(out).length) { snap = out; snapAt = Date.now(); emit([]); }
  return snap;
}
function get(code, pub) {                                                              // the Store item for a series code (first publication that has it unless one is named)
  const es = byCode[code] || [];
  for (const e of es) { if (pub && e.p !== pub) continue; const it = Store.byKey.get(e.p + ':' + e.id); if (it) return it; }
  return null;
}
function status() {
  const out = {};
  CAT.pubs.forEach(p => { const es = byPub[p.code].filter(e => !e.hide), have = es.filter(e => recs.has(e.k)); out[p.code] = { name: p.name, short: p.short, freq: p.freq, part: p.part, total: es.length, loaded: have.length, failed: es.filter(e => errors.has(e.k)).length, newest: have.reduce((m, e) => Math.max(m, recs.get(e.k).fetchedAt), 0) }; });
  return out;
}
window.Feeds = {
  catalog: CAT, entries: ENT, byPub, pubDef, tab: TAB, progress, errors, hidden,
  entriesFor, estimate, load, boot, snapshot, get, status, releaseStamps, loadPart,
  ensureCodes: codes => load(entriesFor(codes)),
  ensureTier: (tier, pubs) => load(entriesFor({ tier, pubs })),
  ensureAll: () => load(ENT.filter(e => !e.hide)),
  has: e => recs.has(e.k),
  cached: () => recs.size,
  snap: () => snap,
  releases: () => relList.slice(),
  clearCache: async () => { recs.clear(); partState.clear(); await idbClear(); if (window.FEEDS_PARTS) Object.keys(window.FEEDS_PARTS).forEach(n => { mergePart(window.FEEDS_PARTS[n]); partState.set(n, Promise.resolve(true)); }); },
  ready: readyP, isReady: () => isReady,
  snapshotInfo: () => snapInfo,
};
})();
